In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

In [ ]:
df = pd.read_csv('career_domain_dataset_5000.csv')

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
print(df['Domain'].nunique())

11

In [ ]:
print(df['Domain'].value_counts())

Domain
Enterprise_Solutions    478
Data_Science            477
Web_Development         473
Mobile_Development      466
Networking              459
Cloud_Computing         454
UI_UX                   453
Cyber_Security          447
IoT_Robotics            432
AI_ML                   418
Software_Engineering    417
Name: count, dtype: int64

In [ ]:
df.head()

,Python,Java,C++,JavaScript,SQL,HTML,CSS,React,Angular,NodeJS,...,Kubernetes,Linux,Networking,CyberSecurity,PenTesting,PowerBI,Tableau,Excel,Statistics,Domain
0,1,0,1,0,1,0,0,0,0,0,...,0,0,0,1,1,0,0,0,0,Software_Engineering
1,1,0,0,1,1,0,0,0,0,0,...,0,0,1,0,0,0,1,0,1,Data_Science
2,0,0,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,Cloud_Computing
3,1,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,AI_ML
4,0,0,0,0,1,0,0,1,0,0,...,0,1,0,0,0,0,0,0,0,Enterprise_Solutions

In [ ]:
x = df.drop(['Domain'],axis=1)
y = df['Domain']

In [ ]:
x

,Python,Java,C++,JavaScript,SQL,HTML,CSS,React,Angular,NodeJS,...,Docker,Kubernetes,Linux,Networking,CyberSecurity,PenTesting,PowerBI,Tableau,Excel,Statistics
0,1,0,1,0,1,0,0,0,0,0,...,0,0,0,0,1,1,0,0,0,0
1,1,0,0,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,1
2,0,0,1,0,0,0,0,0,0,0,...,1,0,1,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
4,0,0,0,0,1,0,0,1,0,0,...,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,1,0,1,0,1,0,0,0,0,0,...,0,0,1,1,1,0,0,0,0,0
4996,1,0,1,0,1,0,0,0,0,0,...,0,0,0,0,1,0,1,0,1,1
4997,0,0,0,0,0,1,1,1,0,0,...,1,0,0,1,0,0,0,1,0,0
4998,0,0,0,1,0,0,0,0,0,0,...,1,0,1,1,1,1,0,0,0,0
4999,0,0,1,0,1,0,0,0,0,0,...,0,0,1,0,0,1,0,0,0,0

In [ ]:
y

0       Software_Engineering
1               Data_Science
2            Cloud_Computing
3                      AI_ML
4       Enterprise_Solutions
                ...
4995              Networking
4996            Data_Science
4997            IoT_Robotics
4998          Cyber_Security
4999            IoT_Robotics
Name: Domain, Length: 4974, dtype: object

In [ ]:
df.isnull().sum()

Python             0
Java               0
C++                0
JavaScript         0
SQL                0
HTML               0
CSS                0
React              0
Angular            0
NodeJS             0
Django             0
Flask              0
SpringBoot         0
Android            0
Kotlin             0
Swift              0
MachineLearning    0
DeepLearning       0
NLP                0
ComputerVision     0
TensorFlow         0
PyTorch            0
AWS                0
Azure              0
GCP                0
Docker             0
Kubernetes         0
Linux              0
Networking         0
CyberSecurity      0
PenTesting         0
PowerBI            0
Tableau            0
Excel              0
Statistics         0
Domain             0
dtype: int64

In [ ]:
y

array([8, 3, 1, ..., 5, 2, 5])

In [ ]:
le =  LabelEncoder()
y_en=le.fit_transform(y)

In [ ]:
import joblib
joblib.dump(le,"label_encoder.pkl")

['label_encoder.pkl']

In [ ]:
le =  LabelEncoder()
y_en2=le.fit_transform(y_en)

In [ ]:
y_en2

array([8, 3, 1, ..., 5, 2, 5])

In [ ]:
print(len(set(y)))

11

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.columns.value_counts()

Python             1
Java               1
C++                1
JavaScript         1
SQL                1
HTML               1
CSS                1
React              1
Angular            1
NodeJS             1
Django             1
Flask              1
SpringBoot         1
Android            1
Kotlin             1
Swift              1
MachineLearning    1
DeepLearning       1
NLP                1
ComputerVision     1
TensorFlow         1
PyTorch            1
AWS                1
Azure              1
GCP                1
Docker             1
Kubernetes         1
Linux              1
Networking         1
CyberSecurity      1
PenTesting         1
PowerBI            1
Tableau            1
Excel              1
Statistics         1
Domain             1
Name: count, dtype: int64

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 4974 entries, 0 to 4999
Data columns (total 36 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Python           4974 non-null   int64
 1   Java             4974 non-null   int64
 2   C++              4974 non-null   int64
 3   JavaScript       4974 non-null   int64
 4   SQL              4974 non-null   int64
 5   HTML             4974 non-null   int64
 6   CSS              4974 non-null   int64
 7   React            4974 non-null   int64
 8   Angular          4974 non-null   int64
 9   NodeJS           4974 non-null   int64
 10  Django           4974 non-null   int64
 11  Flask            4974 non-null   int64
 12  SpringBoot       4974 non-null   int64
 13  Android          4974 non-null   int64
 14  Kotlin           4974 non-null   int64
 15  Swift            4974 non-null   int64
 16  MachineLearning  4974 non-null   int64
 17  DeepLearning     4974 non-null   int64
 18  NLP              4974 non-null   int64
 19  ComputerVision   4974 non-null   int64
 20  TensorFlow       4974 non-null   int64
 21  PyTorch          4974 non-null   int64
 22  AWS              4974 non-null   int64
 23  Azure            4974 non-null   int64
 24  GCP              4974 non-null   int64
 25  Docker           4974 non-null   int64
 26  Kubernetes       4974 non-null   int64
 27  Linux            4974 non-null   int64
 28  Networking       4974 non-null   int64
 29  CyberSecurity    4974 non-null   int64
 30  PenTesting       4974 non-null   int64
 31  PowerBI          4974 non-null   int64
 32  Tableau          4974 non-null   int64
 33  Excel            4974 non-null   int64
 34  Statistics       4974 non-null   int64
 35  Domain           4974 non-null   object
dtypes: int64(35), object(1)
memory usage: 1.4+ MB
None

In [ ]:
print(df['Domain'].value_counts())

Domain
Enterprise_Solutions    478
Data_Science            477
Web_Development         473
Mobile_Development      466
Networking              459
Cloud_Computing         454
UI_UX                   453
Cyber_Security          447
IoT_Robotics            432
AI_ML                   418
Software_Engineering    417
Name: count, dtype: int64

In [ ]:
y

array([8, 3, 1, ..., 5, 2, 5])

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [ ]:
print(x_train.columns.tolist())

['Python', 'Java', 'C++', 'JavaScript', 'SQL', 'HTML', 'CSS', 'React', 'Angular', 'NodeJS', 'Django', 'Flask', 'SpringBoot', 'Android', 'Kotlin', 'Swift', 'MachineLearning', 'DeepLearning', 'NLP', 'ComputerVision', 'TensorFlow', 'PyTorch', 'AWS', 'Azure', 'GCP', 'Docker', 'Kubernetes', 'Linux', 'Networking', 'CyberSecurity', 'PenTesting', 'PowerBI', 'Tableau', 'Excel', 'Statistics']

In [ ]:
x_train

,Python,SQL,Machine_Learning,Deep_Learning,NLP,Computer_Vision,HTML,CSS,JavaScript,React,...,AWS,Docker,Kubernetes,PowerBI,Tableau,Excel,Statistics,DSA,Git,Linux
333,0,0,1,0,0,1,0,1,0,0,...,1,0,1,1,0,1,0,0,0,1
721,0,0,0,0,0,0,1,1,0,0,...,1,0,0,0,0,0,0,0,0,0
1352,1,1,1,1,0,0,0,0,0,0,...,0,0,0,0,1,1,0,1,1,1
1680,0,0,1,0,0,1,0,1,0,0,...,0,0,1,0,1,1,0,0,1,0
156,0,0,1,0,0,0,1,0,0,1,...,0,0,1,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1558,1,0,1,1,0,1,1,0,0,1,...,0,0,0,1,1,0,1,0,1,1
1608,1,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,1,1,1,1,0
493,0,0,0,0,0,0,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
527,0,0,0,0,1,0,0,1,1,0,...,0,0,1,1,0,1,0,0,0,0
1192,0,1,1,0,0,0,0,0,1,0,...,1,0,0,0,0,0,1,0,1,0

In [ ]:
y_train

array([ 6,  5,  3, ...,  0, 10,  3])

In [ ]:
lr  = LogisticRegression()
lr.fit(x_train,y_train)
y_pred1 = lr.predict(x_test)
accuracy = accuracy_score(y_test,y_pred1)
report = classification_report(y_test,y_pred1)

In [ ]:
print(accuracy)

0.8402010050251256

In [ ]:
print(df.shape)
print(x.shape)
print(y.shape)
print(df['Domain'].nunique())

(4974, 36)
(4974, 35)
(4974,)
11

In [ ]:
student_data= x.iloc[[0]]

In [ ]:
predicted_domain_encoded = lr.predict(student_data)[0]


predicted_domain = le.inverse_transform([predicted_domain_encoded])[0]

print("Predicted Domain:", predicted_domain)

career_skills = {}

for domain_name in df["Domain"].unique():

    temp = df[df["Domain"] == domain_name]

    skills = []

    for col in df.columns:

        if col != "Domain":

            if temp[col].mean() >= 0.6:
                skills.append(col)

    career_skills[domain_name] = skills

required_skills = career_skills[predicted_domain]

print("Required Skills:")
print(required_skills)

Predicted Domain: Software_Engineering
Required Skills:
['Python', 'Java', 'C++', 'SQL', 'SpringBoot']

In [ ]:
student_skills = []

for i, col in enumerate(x.columns):

    if student_data.iloc[0][i] == 1:
        student_skills.append(col)

missing_skills = []

for skill in required_skills:

    if skill not in student_skills:
        missing_skills.append(skill)

print("Missing Skills:")
print(missing_skills)

Missing Skills:
['Java', 'SpringBoot']

/tmp/ipykernel_680/977639469.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if student_data.iloc[0][i] == 1:

In [ ]:
import joblib
joblib.dump(lr,"domian_prediction_model2.pkl")

['domian_prediction_model2.pkl']