In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from imblearn.over_sampling import SMOTE

In [ ]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from keras.layers import Dense,Dropout

In [ ]:
df = pd.read_csv('college_student_placement_dataset.csv')

In [ ]:
df.head()

,College_ID,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement
0,CLG0030,107,6.61,6.28,8,No,8,8,4,No
1,CLG0061,97,5.52,5.37,8,No,7,8,0,No
2,CLG0036,109,5.36,5.83,9,No,3,1,1,No
3,CLG0055,122,5.47,5.75,6,Yes,1,6,1,No
4,CLG0004,96,7.91,7.69,7,No,8,10,2,No

In [ ]:
df = df.drop(columns=['College_ID'])

In [ ]:
df.head()

,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement
0,107,6.61,6.28,8,No,8,8,4,No
1,97,5.52,5.37,8,No,7,8,0,No
2,109,5.36,5.83,9,No,3,1,1,No
3,122,5.47,5.75,6,Yes,1,6,1,No
4,96,7.91,7.69,7,No,8,10,2,No

In [ ]:
df.isnull().sum()

IQ                        0
Prev_Sem_Result           0
CGPA                      0
Academic_Performance      0
Internship_Experience     0
Extra_Curricular_Score    0
Communication_Skills      0
Projects_Completed        0
Placement                 0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
le = LabelEncoder()
df['Placement'] = le.fit_transform(df['Placement'])
df['Internship_Experience'] = le.fit_transform(df['Internship_Experience'])

In [ ]:
df.head()

,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement
0,107,6.61,6.28,8,0,8,8,4,0
1,97,5.52,5.37,8,0,7,8,0,0
2,109,5.36,5.83,9,0,3,1,1,0
3,122,5.47,5.75,6,1,1,6,1,0
4,96,7.91,7.69,7,0,8,10,2,0

In [ ]:
df.Placement.value_counts()

Placement
0    8341
1    1659
Name: count, dtype: int64

In [ ]:
df.head()

,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement
0,107,6.61,6.28,8,0,8,8,4,0
1,97,5.52,5.37,8,0,7,8,0,0
2,109,5.36,5.83,9,0,3,1,1,0
3,122,5.47,5.75,6,1,1,6,1,0
4,96,7.91,7.69,7,0,8,10,2,0

In [ ]:
x = df.drop(columns=['Placement'])
y = df.Placement

In [ ]:
print(x.shape)

(10000, 8)

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [ ]:
print(x_train.columns.tolist())

['IQ', 'Prev_Sem_Result', 'CGPA', 'Academic_Performance', 'Internship_Experience', 'Extra_Curricular_Score', 'Communication_Skills', 'Projects_Completed']

In [ ]:
x_train

,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed
8856,103,7.88,8.03,8,0,8,9,3
1545,107,9.37,9.12,6,0,1,8,0
8136,86,7.69,8.12,7,0,7,9,3
7768,110,6.48,6.20,3,0,0,1,4
7782,101,9.30,9.44,7,0,4,1,2
...,...,...,...,...,...,...,...,...
1099,105,7.96,7.85,6,0,9,10,4
2514,98,8.87,9.16,1,1,9,2,2
6637,80,7.76,7.81,9,0,2,3,1
2575,83,9.77,9.68,1,0,2,2,3
7336,99,7.41,7.50,8,0,10,3,5

In [ ]:
x_test

,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed
7878,91,8.94,8.69,2,0,8,10,3
3224,104,9.27,9.30,9,0,3,6,1
1919,92,5.90,5.44,3,1,4,6,2
4432,103,9.16,8.72,5,1,0,6,0
4835,101,5.38,5.21,2,0,4,4,2
...,...,...,...,...,...,...,...,...
9073,122,6.46,6.15,2,0,5,1,4
8584,96,5.64,5.81,6,0,4,9,5
5390,89,7.07,6.66,1,1,10,1,5
5092,79,8.20,8.34,6,1,6,1,1
2964,118,9.89,9.83,6,0,0,8,4

In [ ]:
y_train

8856    1
1545    0
8136    1
7768    0
7782    0
       ..
1099    0
2514    0
6637    0
2575    0
7336    0
Name: Placement, Length: 8000, dtype: int64

In [ ]:
y_test

7878    1
3224    0
1919    0
4432    0
4835    0
       ..
9073    0
8584    0
5390    0
5092    0
2964    1
Name: Placement, Length: 2000, dtype: int64

In [ ]:
smote = SMOTE(random_state=42)
x_train_resampled, y_train_resampled = smote.fit_resample(x_train, y_train)

In [ ]:
y_train_resampled.size

13348

In [ ]:
print(y_train.value_counts())
print(y_train_resampled.value_counts())

Placement
0    6674
1    1326
Name: count, dtype: int64
Placement
1    6674
0    6674
Name: count, dtype: int64

In [ ]:
pip install -U keras-tuner

Collecting keras-tuner
  Downloading keras_tuner-1.4.8-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (3.13.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (26.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (2.32.4)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: grpcio in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.82.1)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio->keras-tuner) (4.16.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.19.1)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2026.6.17)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)
Downloading keras_tuner-1.4.8-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 1.0 MB/s eta 0:00:00
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.8 kt-legacy-1.0.5

In [ ]:
import kerastuner as kt

/tmp/ipykernel_3361/1654478174.py:1: DeprecationWarning: `import kerastuner` is deprecated, please use `import keras_tuner`.
  import kerastuner as kt

In [ ]:
def build_model(hp):
  model  = Sequential()
  counter = 0
  for i in range(hp.Int('num_layers',min_value=1,max_value=10)):
    if counter == 0:
      model.add(Dense(hp.Int('units' + str(i),min_value=8,max_value=128,step=8),activation = hp.Choice('activation' + str(i),values=['relu','tanh','sigmoid']),input_dim=8))
      model.add(Dropout(hp.Choice('dropout' + str(i),values=[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))

    else:
      model.add(Dense(hp.Int('units' + str(i),min_value=8,max_value=128,step=8),activation = hp.Choice('activation' + str(i),values=['relu','tanh','sigmoid'])))
      model.add(Dropout(hp.Choice('dropout' + str(i),values=[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))


    counter+=1
  model.add(Dense(1,activation='sigmoid'))
  model.compile(optimizer=hp.Choice('optimizer',values=['adam','rmsprop','sgd','nadam']),loss ='binary_crossentropy',metrics=['accuracy'])
  return model

In [ ]:
tuner = kt.RandomSearch(build_model,objective='val_accuracy',max_trials=10,directory='mydir')
tuner.search(x_train_resampled,y_train_resampled,epochs=5,validation_data=(x_test,y_test))

Trial 10 Complete [00h 00m 07s]
val_accuracy: 0.8335000276565552

Best val_accuracy So Far: 0.8339999914169312
Total elapsed time: 00h 01m 10s

In [ ]:
model = tuner.get_best_models(num_models=1)[0]
model.fit(x_train_resampled,y_train_resampled,epochs=90,initial_epoch=6,validation_data=(x_test,y_test))

Epoch 7/90

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5996 - loss: 0.6639 - val_accuracy: 0.6585 - val_loss: 0.6530
Epoch 8/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6149 - loss: 0.6532 - val_accuracy: 0.8365 - val_loss: 0.4878
Epoch 9/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6290 - loss: 0.6404 - val_accuracy: 0.7835 - val_loss: 0.5210
Epoch 10/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6348 - loss: 0.6395 - val_accuracy: 0.8360 - val_loss: 0.4628
Epoch 11/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6410 - loss: 0.6317 - val_accuracy: 0.8375 - val_loss: 0.4486
Epoch 12/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6384 - loss: 0.6319 - val_accuracy: 0.8055 - val_loss: 0.4668
Epoch 13/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6492 - loss: 0.6276 - val_accuracy: 0.6600 - val_loss: 0.5946
Epoch 14/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6503 - loss: 0.6245 - val_accuracy: 0.8385 - val_loss: 0.4257
Epoch 15/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6550 - loss: 0.6203 - val_accuracy: 0.8195 - val_loss: 0.4685
Epoch 16/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6539 - loss: 0.6230 - val_accuracy: 0.8010 - val_loss: 0.4798
Epoch 17/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6620 - loss: 0.6179 - val_accuracy: 0.7545 - val_loss: 0.5417
Epoch 18/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6609 - loss: 0.6145 - val_accuracy: 0.5860 - val_loss: 0.6731
Epoch 19/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6668 - loss: 0.6098 - val_accuracy: 0.7500 - val_loss: 0.5238
Epoch 20/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6630 - loss: 0.6105 - val_accuracy: 0.2250 - val_loss: 1.0203
Epoch 21/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6689 - loss: 0.6084 - val_accuracy: 0.4685 - val_loss: 0.7147
Epoch 22/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6657 - loss: 0.6074 - val_accuracy: 0.8395 - val_loss: 0.4358
Epoch 23/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6706 - loss: 0.6022 - val_accuracy: 0.7255 - val_loss: 0.5322
Epoch 24/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.6730 - loss: 0.6054 - val_accuracy: 0.4325 - val_loss: 0.7871
Epoch 25/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6770 - loss: 0.5985 - val_accuracy: 0.6040 - val_loss: 0.6528
Epoch 26/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6712 - loss: 0.6015 - val_accuracy: 0.8340 - val_loss: 0.4220
Epoch 27/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6741 - loss: 0.5966 - val_accuracy: 0.2755 - val_loss: 0.9008
Epoch 28/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6773 - loss: 0.5974 - val_accuracy: 0.8475 - val_loss: 0.4047
Epoch 29/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6822 - loss: 0.5943 - val_accuracy: 0.7205 - val_loss: 0.5283
Epoch 30/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6846 - loss: 0.5887 - val_accuracy: 0.8360 - val_loss: 0.4146
Epoch 31/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6816 - loss: 0.5903 - val_accuracy: 0.8400 - val_loss: 0.4190
Epoch 32/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6852 - loss: 0.5864 - val_accuracy: 0.6695 - val_loss: 0.6348
Epoch 33/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6859 - loss: 0.5839 - val_accuracy: 0.7715 - val_loss: 0.4893
Epoch 34/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6847 - loss: 0.5837 - val_accuracy: 0.8365 - val_loss: 0.4191
Epoch 35/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6935 - loss: 0.5799 - val_accuracy: 0.8395 - val_loss: 0.4061
Epoch 36/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6875 - loss: 0.5841 - val_accuracy: 0.8335 - val_loss: 0.4147
Epoch 37/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6832 - loss: 0.5908 - val_accuracy: 0.2525 - val_loss: 1.0196
Epoch 38/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6844 - loss: 0.5894 - val_accuracy: 0.8345 - val_loss: 0.4100
Epoch 39/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6856 - loss: 0.5839 - val_accuracy: 0.7990 - val_loss: 0.5688
Epoch 40/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6916 - loss: 0.5805 - val_accuracy: 0.5725 - val_loss: 0.7343
Epoch 41/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6855 - loss: 0.5823 - val_accuracy: 0.4960 - val_loss: 0.8676
Epoch 42/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6921 - loss: 0.5839 - val_accuracy: 0.6005 - val_loss: 0.6803
Epoch 43/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6904 - loss: 0.5750 - val_accuracy: 0.8210 - val_loss: 0.4629
Epoch 44/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6991 - loss: 0.5700 - val_accuracy: 0.8420 - val_loss: 0.4096
Epoch 45/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6956 - loss: 0.5707 - val_accuracy: 0.8130 - val_loss: 0.4787
Epoch 46/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6927 - loss: 0.5762 - val_accuracy: 0.5445 - val_loss: 0.8010
Epoch 47/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6995 - loss: 0.5630 - val_accuracy: 0.4445 - val_loss: 1.0464
Epoch 48/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.6951 - loss: 0.5735 - val_accuracy: 0.7325 - val_loss: 0.5431
Epoch 49/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7001 - loss: 0.5657 - val_accuracy: 0.5395 - val_loss: 0.8362
Epoch 50/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7003 - loss: 0.5600 - val_accuracy: 0.7800 - val_loss: 0.5770
Epoch 51/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7049 - loss: 0.5584 - val_accuracy: 0.8345 - val_loss: 0.4316
Epoch 52/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7009 - loss: 0.5582 - val_accuracy: 0.5300 - val_loss: 0.8858
Epoch 53/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7083 - loss: 0.5547 - val_accuracy: 0.8450 - val_loss: 0.3982
Epoch 54/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7070 - loss: 0.5576 - val_accuracy: 0.8300 - val_loss: 0.4757
Epoch 55/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7078 - loss: 0.5502 - val_accuracy: 0.6950 - val_loss: 0.6414
Epoch 56/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7092 - loss: 0.5568 - val_accuracy: 0.8020 - val_loss: 0.4515
Epoch 57/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7100 - loss: 0.5497 - val_accuracy: 0.7960 - val_loss: 0.4739
Epoch 58/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7116 - loss: 0.5459 - val_accuracy: 0.8365 - val_loss: 0.4284
Epoch 59/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7143 - loss: 0.5490 - val_accuracy: 0.8255 - val_loss: 0.4672
Epoch 60/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7164 - loss: 0.5451 - val_accuracy: 0.8335 - val_loss: 0.4158
Epoch 61/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7209 - loss: 0.5427 - val_accuracy: 0.6670 - val_loss: 0.5923
Epoch 62/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7231 - loss: 0.5385 - val_accuracy: 0.8190 - val_loss: 0.5572
Epoch 63/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7151 - loss: 0.5479 - val_accuracy: 0.2545 - val_loss: 1.2501
Epoch 64/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7149 - loss: 0.5485 - val_accuracy: 0.6165 - val_loss: 0.6241
Epoch 65/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7285 - loss: 0.5374 - val_accuracy: 0.7845 - val_loss: 0.4833
Epoch 66/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7294 - loss: 0.5300 - val_accuracy: 0.8310 - val_loss: 0.4062
Epoch 67/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7259 - loss: 0.5359 - val_accuracy: 0.6275 - val_loss: 0.6655
Epoch 68/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7257 - loss: 0.5373 - val_accuracy: 0.6485 - val_loss: 0.6589
Epoch 69/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7314 - loss: 0.5325 - val_accuracy: 0.8045 - val_loss: 0.4894
Epoch 70/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7287 - loss: 0.5292 - val_accuracy: 0.8335 - val_loss: 0.4004
Epoch 71/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7059 - loss: 0.5562 - val_accuracy: 0.6845 - val_loss: 0.5907
Epoch 72/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7209 - loss: 0.5474 - val_accuracy: 0.5475 - val_loss: 0.6977
Epoch 73/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7159 - loss: 0.5420 - val_accuracy: 0.7615 - val_loss: 0.4551
Epoch 74/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7208 - loss: 0.5432 - val_accuracy: 0.7800 - val_loss: 0.4529
Epoch 75/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7215 - loss: 0.5361 - val_accuracy: 0.2140 - val_loss: 1.1893
Epoch 76/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7117 - loss: 0.5487 - val_accuracy: 0.7525 - val_loss: 0.4827
Epoch 77/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7245 - loss: 0.5354 - val_accuracy: 0.8130 - val_loss: 0.4129
Epoch 78/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7215 - loss: 0.5362 - val_accuracy: 0.8055 - val_loss: 0.4439
Epoch 79/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7237 - loss: 0.5330 - val_accuracy: 0.5270 - val_loss: 0.7260
Epoch 80/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7261 - loss: 0.5280 - val_accuracy: 0.7730 - val_loss: 0.4784
Epoch 81/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7270 - loss: 0.5250 - val_accuracy: 0.8240 - val_loss: 0.3900
Epoch 82/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7313 - loss: 0.5242 - val_accuracy: 0.5790 - val_loss: 0.6956
Epoch 83/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7239 - loss: 0.5337 - val_accuracy: 0.7820 - val_loss: 0.4393
Epoch 84/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7296 - loss: 0.5263 - val_accuracy: 0.8415 - val_loss: 0.3795
Epoch 85/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7300 - loss: 0.5210 - val_accuracy: 0.6800 - val_loss: 0.5404
Epoch 86/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7316 - loss: 0.5187 - val_accuracy: 0.7170 - val_loss: 0.5363
Epoch 87/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7411 - loss: 0.5188 - val_accuracy: 0.8040 - val_loss: 0.4280
Epoch 88/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7386 - loss: 0.5164 - val_accuracy: 0.8470 - val_loss: 0.3645
Epoch 89/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7412 - loss: 0.5140 - val_accuracy: 0.6955 - val_loss: 0.5413
Epoch 90/90
418/418 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7349 - loss: 0.5180 - val_accuracy: 0.8370 - val_loss: 0.3683

In [ ]:
y_pred4 = model.predict(x_test)
y_pred4 = (y_pred4 > 0.5).astype(int)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

In [ ]:
print(classification_report(y_test,y_pred4))

              precision    recall  f1-score   support

           0       0.91      0.89      0.90      1667
           1       0.51      0.56      0.53       333

    accuracy                           0.84      2000
   macro avg       0.71      0.72      0.72      2000
weighted avg       0.84      0.84      0.84      2000

In [ ]:
print(accuracy_score(y_test,y_pred4))

0.837

In [ ]:
model.save("placement_model.keras")